[phases.setup]
nixPkgs = ["ffmpeg", "python3", "curl"]

[phases.build]
cmds = [
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp",
  "chmod +x yt-dlp"
]

[start]
cmd = "node index.js"
